FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential
RUN apt-get install -y libodbc2
RUN apt-get install -y curl
RUN apt-get install -y sudo
RUN apt-get install -y apt-transport-https
RUN apt-get install -y gnupg
# Install ODBC Driver securely
RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" > /etc/apt/sources.list.d/microsoft.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN . ~/.bashrc

# Install Poetry
RUN pip install --no-cache-dir poetry==2.2.1

# Make Poetry install to the global env instead of creating a venv
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --no-interaction --no-ansi --only mcp_server

COPY . .

EXPOSE 8001

CMD ["sh", "-c", "poetry run uvicorn mcp_server.server:mcp_app.http_app --host 0.0.0.0 --port 8001"]
